packages:
  globals-common: !include globals-common.yaml
  web-server-common: !include web-server-common.yaml
  Diagnostic-common: !include diagnostic-entities-common.yaml
  http-update-common: !include http-ota-update-common.yaml

logger:
api:
ota:
  - platform: web_server
    on_error:
      - button.press: restart_button

safe_mode:
captive_portal:
wifi:
  ap:
    ssid: "${device_name}_Setup"
    password: "pb1234"
mdns: # make bulb announce self "bulb.local"

# Apply static IP at boot
on_boot:
  priority: 100
  then:
    - lambda: |-
        if (!id(static_ip).empty()) {
          IPAddress ip_addr, gw_addr, sn_addr;
          ip_addr.fromString(id(static_ip).c_str());
          gw_addr.fromString(id(static_gateway).c_str());
          if (!id(static_subnet).empty()) sn_addr.fromString(id(static_subnet).c_str());
          else sn_addr.fromString("255.255.255.0");
          WiFi.config(ip_addr, gw_addr, sn_addr);
        }

time:
  - platform: sntp
    id: sntp_time
    timezone: "UTC"  # default until user sets it
