globals:
  - id: static_ip
    type: std::string
    restore_value: true
    initial_value: ""
  - id: static_gateway
    type: std::string
    restore_value: true
    initial_value: ""
  - id: static_subnet
    type: std::string
    restore_value: true
    initial_value: ""
